all:
    hosts:
        ru-yc-3:
            ansible_host: 158.160.5.113
            ansible_user: kit
            xui_panel_port: 60923
            inbound:
                port: 443
                tag: vless-in-ru-yc-3
                reality_target: codewizards.pro:443
                reality_server_names:
                    - codewizards.pro
                    - www.codewizards.pro
                fingerprint: firefox
