xui_image: ghcr.io/mhsanaei/3x-ui:latest
xui_container_name: xui
xui_db_path: /etc/x-ui
xui_sub_port: 2096
xui_sub_path: /sub
xui_sub_https: false
clients:
    - name: alice
    - name: bob
    - name: misha
    - name: default
paths:
    - name: direct-singapore
      hops:
        - node-singapore
    - name: relay-frankfurt-singapore
      hops:
        - node-frankfurt
        - node-singapore
    - name: ru-yc-1
      hops:
        - ru-yc-1
    - name: ru-yc-2-direct
      hops:
        - ru-yc-2
    - name: ru-yc-3
      hops:
        - ru-yc-3
